// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:flutter/foundation.dart';
import 'package:firebase_core/firebase_core.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'run FlutterFire CLI again to configure it.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBH_MAZRCfFYtdfRlngizBjRPBMpNAKbFo',
    appId: '1:526881957709:web:d239d17009479460783904',
    messagingSenderId: '526881957709',
    projectId: 'myapp-final-82a1c',
    authDomain: 'myapp-final-82a1c.firebaseapp.com',
    storageBucket: 'myapp-final-82a1c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZW0MrUr7wjKiM5sCwv75sjdw5xOoRznM',
    appId: '1:526881957709:android:57113d48039fc14d783904',
    messagingSenderId: '526881957709',
    projectId: 'myapp-final-82a1c',
    storageBucket: 'myapp-final-82a1c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgC-oFLC4yt5dZqv7-nhf9QHuK37pW2JY',
    appId: '1:526881957709:ios:17d6d41a04819a47783904',
    messagingSenderId: '526881957709',
    projectId: 'myapp-final-82a1c',
    storageBucket: 'myapp-final-82a1c.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgC-oFLC4yt5dZqv7-nhf9QHuK37pW2JY',
    appId: '1:526881957709:ios:17d6d41a04819a47783904',
    messagingSenderId: '526881957709',
    projectId: 'myapp-final-82a1c',
    storageBucket: 'myapp-final-82a1c.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBH_MAZRCfFYtdfRlngizBjRPBMpNAKbFo',
    appId: '1:526881957709:web:675ae8611c99be39783904',
    messagingSenderId: '526881957709',
    projectId: 'myapp-final-82a1c',
    authDomain: 'myapp-final-82a1c.firebaseapp.com',
    storageBucket: 'myapp-final-82a1c.firebasestorage.app',
  );
}