// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:flutter/foundation.dart';
import 'package:firebase_core/firebase_core.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'run FlutterFire CLI again to configure it.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1xX4_OsD8sDCBFn5Dc0reMC2L3uHhqC0',
    appId: '1:1060091689567:web:9dd115b3dcffd9f21939ea',
    messagingSenderId: '1060091689567',
    projectId: 'chat-app-d9fc3',
    authDomain: 'chat-app-d9fc3.firebaseapp.com',
    storageBucket: 'chat-app-d9fc3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5c6114nd1oM5zGkL4HlQCD-exd8-sy0M',
    appId: '1:1060091689567:android:f122734776d794701939ea',
    messagingSenderId: '1060091689567',
    projectId: 'chat-app-d9fc3',
    storageBucket: 'chat-app-d9fc3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0DEltBkvXYYV-weVM1X5sRhyIapzpi2o',
    appId: '1:1060091689567:ios:07d0ed0297b965c61939ea',
    messagingSenderId: '1060091689567',
    projectId: 'chat-app-d9fc3',
    storageBucket: 'chat-app-d9fc3.firebasestorage.app',
    androidClientId: '1060091689567-vu0ft9r62g7dis06eijerna56fg26r26.apps.googleusercontent.com',
    iosClientId: '1060091689567-dsl5uq1m2r9o84id0vpt64qmv5n8erpg.apps.googleusercontent.com',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0DEltBkvXYYV-weVM1X5sRhyIapzpi2o',
    appId: '1:1060091689567:ios:07d0ed0297b965c61939ea',
    messagingSenderId: '1060091689567',
    projectId: 'chat-app-d9fc3',
    storageBucket: 'chat-app-d9fc3.firebasestorage.app',
    androidClientId: '1060091689567-vu0ft9r62g7dis06eijerna56fg26r26.apps.googleusercontent.com',
    iosClientId: '1060091689567-dsl5uq1m2r9o84id0vpt64qmv5n8erpg.apps.googleusercontent.com',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1xX4_OsD8sDCBFn5Dc0reMC2L3uHhqC0',
    appId: '1:1060091689567:web:d8ec7cb1f29782e61939ea',
    messagingSenderId: '1060091689567',
    projectId: 'chat-app-d9fc3',
    authDomain: 'chat-app-d9fc3.firebaseapp.com',
    storageBucket: 'chat-app-d9fc3.firebasestorage.app',
  );

}